<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 24 24" aria-hidden="true">
  <rect x="2" y="2" width="20" height="20" rx="5" fill="white" stroke="black" />
  <path d="M7 7h10l-10 10h10" stroke="#e1192a" stroke-width="2" fill="none"/>
</svg>
