# Netlify configuration for ZetaConvert

[build]
  publish = "."

# ---------- Redirects ----------
# Rutas limpias (por si faltan extensiones)
[[redirects]]
  from = "/converters"
  to   = "/converters/"
  status = 301
  force = true

[[redirects]]
  from = "/text"
  to   = "/text/"
  status = 301
  force = true

[[redirects]]
  from = "/three"
  to   = "/three/"
  status = 301
  force = true

# Proxy backend (Render)
[[redirects]]
  from = "/api/*"
  to   = "https://zetaconvert-backend.onrender.com/:splat"
  status = 200
  force = true

# ---------- Headers ----------
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    # CSP: ajusta si usas más orígenes (ej. analytics/ads)
    Content-Security-Policy = "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self' https://zetaconvert-backend.onrender.com; object-src 'none'; base-uri 'self'; frame-ancestors 'none';"

# Cache agresivo para estáticos fingerprinted (si los usas)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
